#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Chronos-2 (time-series foundation model) zero-shot baseline for the
evo-xxltraffic continual-forecasting benchmark.

This is a *standalone* evaluator. It does NOT touch main.py / src/model/model.py
/ the trainer at all — Chronos-2 is a pretrained foundation model that forecasts
zero-shot, so the gradient-descent retrain/incremental machinery in main.py does
not apply. Instead we reproduce, exactly, the test split + windowing + metric
that src/trainer/default_trainer.py::test_model and utils/metric.py::cal_metric
use, so the numbers are directly comparable to the other baselines' tables.

Key fidelity points (verified against the precomputed FastData npz):
  * The FastData npz were generated by utils/data_convert.generate_samples with
    the PEMS-style 31*288 day slice. We rebuild the *raw-scale* test windows the
    same way (slice -> test_idx = [0.8t, t) -> generate_dataset), so we can feed
    Chronos the unnormalised context it expects and compare against the raw
    targets. We assert our reconstruction matches the npz test_x (after z-score)
    and test_y (raw) before trusting it.
  * Metrics are the *cumulative-horizon* MAE/RMSE/MAPE at T=3,6,12 and the Avg
    over T=1..12, masked at null_val=0 — identical to utils/metric.cal_metric.

Usage (single dataset, all years):
    python chronos_baseline.py --dataset pems03 --gpuid 0

Usage (one (dataset, year) shard — what the katana FIFO dispatcher calls):
    python chronos_baseline.py --dataset pems03 --year 2001 --gpuid 0

Outputs (under --out-dir, default run_logs/chronos):
    <dataset>/<dataset>_<year>.json   per-(dataset,year) metrics
    <dataset>/<dataset>_results.csv   appended one row per year (flock-guarded)
"""
import os
import sys
import csv
import json
import time
import fcntl
import argparse

import numpy as np

# src/ is on the path in main.py via sys.path.append("src/"); we only need the
# pure-numpy metric helpers, so import them directly without dragging in torch_geometric.
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "utils"))
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))

X_LEN = 12
Y_LEN = 12
DAYS = 31            # generate_samples(days=31, ...) in main.py
STEPS_PER_DAY = 288  # 5-min PEMS sampling


# --------------------------------------------------------------------------- #
# Metric helpers — byte-for-byte copies of utils/metric.py so this script has
# no import-time dependency on the (torch_geometric-heavy) src package.
# --------------------------------------------------------------------------- #
def mask_np(array, null_val):
    if np.isnan(null_val):
        return (~np.isnan(array)).astype("float32")
    return np.not_equal(array, null_val).astype("float32")


def masked_mape_np(y_true, y_pred, null_val=np.nan):
    with np.errstate(divide="ignore", invalid="ignore"):
        mask = mask_np(y_true, null_val)
        mask /= mask.mean()
        mape = np.abs((y_pred - y_true) / y_true)
        mape = np.nan_to_num(mask * mape)
        return np.mean(mape) * 100


def masked_mse_np(y_true, y_pred, null_val=np.nan):
    mask = mask_np(y_true, null_val)
    mask /= mask.mean()
    mse = (y_true - y_pred) ** 2
    return np.mean(np.nan_to_num(mask * mse))


def masked_mae_np(y_true, y_pred, null_val=np.nan):
    mask = mask_np(y_true, null_val)
    mask /= mask.mean()
    mae = np.abs(y_true - y_pred)
    return np.mean(np.nan_to_num(mask * mae))


def cal_metric(ground_truth, prediction):
    """Cumulative-horizon metrics, identical to utils/metric.cal_metric.

    ground_truth / prediction: (num_samples, num_nodes, Y_LEN), raw scale.
    Returns dict {"3":{MAE,RMSE,MAPE}, "6":..., "12":..., "Avg":...}.
    """
    mae_list, rmse_list, mape_list = [], [], []
    out = {}
    for i in range(1, Y_LEN + 1):
        mae = masked_mae_np(ground_truth[:, :, :i], prediction[:, :, :i], 0)
        rmse = masked_mse_np(ground_truth[:, :, :i], prediction[:, :, :i], 0) ** 0.5
        mape = masked_mape_np(ground_truth[:, :, :i], prediction[:, :, :i], 0)
        mae_list.append(mae)
        rmse_list.append(rmse)
        mape_list.append(mape)
        if i in (3, 6, 12):
            out[str(i)] = {"MAE": float(mae), "RMSE": float(rmse), "MAPE": float(mape)}
    out["Avg"] = {
        "MAE": float(np.mean(mae_list)),
        "RMSE": float(np.mean(rmse_list)),
        "MAPE": float(np.mean(mape_list)),
    }
    return out


# --------------------------------------------------------------------------- #
# Data: rebuild the exact raw-scale test windows used by generate_samples.
# --------------------------------------------------------------------------- #
def z_score(data):
    """Copy of utils/data_convert.z_score (for the reconstruction sanity check)."""
    mean = np.nanmean(data)
    std = np.nanstd(data)
    if not np.isfinite(std) or std < 1e-8:
        std = 1.0
    out = (data - mean) / std
    return np.nan_to_num(out, nan=0.0, posinf=0.0, neginf=0.0)


def generate_dataset(data, idx, x_len=X_LEN, y_len=Y_LEN):
    """Copy of utils/data_convert.generate_dataset."""
    res = data[idx]
    node_size = data.shape[1]
    t = len(idx) - 1
    x_index, y_index = [], []
    for i in range(t, 0, -1):
        if i - x_len - y_len >= 0:
            x_index.extend(list(range(i - x_len - y_len, i - y_len)))
            y_index.extend(list(range(i - y_len, i)))
    x_index = np.asarray(x_index)
    y_index = np.asarray(y_index)
    x = res[x_index].reshape((-1, x_len, node_size))
    y = res[y_index].reshape((-1, y_len, node_size))
    return x, y


def build_test_windows(raw_data_path, year, fast_data_path=None, verify=True):
    """Reconstruct raw-scale (test_x, test_y) for one year.

    test_x: (S, X_LEN, N) raw-scale context (fed to Chronos)
    test_y: (S, Y_LEN, N) raw-scale targets (ground truth)
    If verify and the FastData npz exists, assert z_score(test_x)==npz.test_x and
    test_y==npz.test_y so we know the windowing matches the trained baselines.
    """
    raw = np.load(os.path.join(raw_data_path, f"{year}.npz"))["x"]
    # PEMS (5-min) keeps the 31-day slice (DAYS*288). TFNSW is hourly and a whole
    # year is < DAYS*288 rows, so it uses the FULL year — matching how its FastData
    # was built (the 31-day slice in generate_samples is PEMS-only). The `verify`
    # assert below confirms the reconstruction matches the npz either way.
    data = raw[0:DAYS * STEPS_PER_DAY, :] if raw.shape[0] > DAYS * STEPS_PER_DAY else raw
    t = data.shape[0]
    test_idx = list(range(int(t * 0.8), t))
    test_x, test_y = generate_dataset(data, test_idx)
    test_y = np.nan_to_num(test_y, nan=0.0, posinf=0.0, neginf=0.0)

    if verify and fast_data_path is not None:
        fp = os.path.join(fast_data_path, f"{year}.npz")
        if os.path.exists(fp):
            ref = np.load(fp, allow_pickle=True)
            assert test_x.shape == ref["test_x"].shape, (
                f"shape mismatch {test_x.shape} vs {ref['test_x'].shape}")
            assert np.allclose(z_score(test_x), ref["test_x"], atol=1e-3), \
                "reconstructed test_x (z-scored) does not match FastData npz"
            assert np.allclose(test_y, ref["test_y"], atol=1e-3), \
                "reconstructed test_y does not match FastData npz"
    return test_x, test_y


# --------------------------------------------------------------------------- #
# Chronos-2 forecasting.
#
# API (chronos-forecasting 2.x, Chronos2Pipeline.predict_quantiles):
#   inputs : (B, n_variates, history_len) tensor, OR a list whose elements are
#            2-D (n_variates, history_len) arrays. When n_variates>1 the model
#            shares information across the variates of that element (multivariate
#            zero-shot forecasting — Chronos-2's headline feature).
#   returns (quantiles, mean); mean[i] has shape (n_variates, pred_len).
# We use the MEAN (point) forecast — the trained ST baselines minimise MSE, so
# the conditional mean is the directly-comparable point estimate.
#
# Two modes:
#   univariate   : each (window, node) is an independent 1-variate series.
#   multivariate : nodes are split into spatially-coherent GROUPS (via the
#                  per-year adjacency graph); each (window, group) is one
#                  multivariate task so Chronos-2 shares info across nearby
#                  sensors. Feeding all N nodes at once is out-of-distribution
#                  (pretraining group size ~100s) and memory-prohibitive for the
#                  large late-year graphs (pems07 2025 has 4888 nodes), hence
#                  grouping with a modest group size.
# --------------------------------------------------------------------------- #
def load_pipeline(model_id, device, dtype):
    from chronos import BaseChronosPipeline
    return BaseChronosPipeline.from_pretrained(
        model_id, device_map=device, torch_dtype=dtype)


def impute_windows(test_x):
    """test_x: (S, X_LEN, N). Fill missing (NaN/inf) entries of each (s, node)
    length-X_LEN context with that context's own mean; all-missing -> 0.0.
    Returns (imputed float32, n_bad) where n_bad counts (s, node) series touched."""
    x = np.where(np.isfinite(test_x), test_x, np.nan).astype(np.float64)
    bad_mask = np.isnan(x).any(axis=1)            # (S, N)
    n_bad = int(bad_mask.sum())
    if n_bad:
        mean = np.nanmean(x, axis=1, keepdims=True)   # (S, 1, N)
        mean = np.where(np.isfinite(mean), mean, 0.0)
        x = np.where(np.isnan(x), mean, x)
    return x.astype(np.float32), n_bad


def index_groups(n_nodes, group_size):
    """Contiguous node-index chunks of size `group_size`."""
    return [np.arange(i, min(i + group_size, n_nodes))
            for i in range(0, n_nodes, group_size)]


def graph_groups(adj, group_size):
    """Spatially-coherent groups via a BFS traversal of the adjacency graph.

    adj: (N, N) per-year adjacency ('x' in <year>_adj.npz). We BFS across the
    graph (deterministic, seeded by ascending node index, hopping to the next
    unvisited node between components) to get an ordering where neighbours are
    adjacent, then chunk that ordering into groups of `group_size`. Keeps
    spatially-close sensors together so the in-group multivariate attention sees
    correlated series.
    """
    import collections
    n = adj.shape[0]
    neigh = [np.nonzero(adj[i])[0] for i in range(n)]
    visited = np.zeros(n, dtype=bool)
    order = []
    for seed in range(n):
        if visited[seed]:
            continue
        dq = collections.deque([seed])
        visited[seed] = True
        while dq:
            u = dq.popleft()
            order.append(u)
            for v in neigh[u]:
                if not visited[v]:
                    visited[v] = True
                    dq.append(int(v))
    order = np.asarray(order, dtype=np.int64)
    return [order[i:i + group_size] for i in range(0, n, group_size)]


def forecast_univariate(pipeline, test_x, batch_size):
    """test_x: (S, X_LEN, N) imputed raw context. Returns pred (S, N, Y_LEN)."""
    import torch
    S, _, N = test_x.shape
    # (S, X_LEN, N) -> (S, N, X_LEN) -> (S*N, X_LEN); row order matches gt[s, n].
    ctx = np.ascontiguousarray(np.transpose(test_x, (0, 2, 1)).reshape(S * N, X_LEN))
    B = ctx.shape[0]
    chunk = max(batch_size, 4096)
    out = np.empty((B, Y_LEN), dtype=np.float32)
    for start in range(0, B, chunk):
        end = min(start + chunk, B)
        inp = torch.from_numpy(ctx[start:end]).unsqueeze(1)  # (c, 1, X_LEN)
        _, mean = pipeline.predict_quantiles(
            inp, prediction_length=Y_LEN, quantile_levels=[0.5],
            batch_size=batch_size)
        m = torch.stack([t[0] for t in mean], dim=0).float().cpu().numpy()  # (c, Y_LEN)
        out[start:end] = m
        if (start // chunk) % 10 == 0 or end == B:
            print(f"[chronos]   forecast {end}/{B} series", flush=True)
    return out.reshape(S, N, Y_LEN)


def forecast_multivariate(pipeline, test_x, groups, batch_size):
    """test_x: (S, X_LEN, N) imputed raw context. `groups`: list of node-index
    arrays. Each (window, group) is one multivariate task of shape (|group|, X_LEN).
    Returns pred (S, N, Y_LEN)."""
    S, _, N = test_x.shape
    G = max(len(g) for g in groups)
    out = np.empty((S, N, Y_LEN), dtype=np.float32)
    # Chunk tasks so each predict call handles ~4096 series (variates summed).
    tasks_per_call = max(1, 4096 // G)
    total_tasks = S * len(groups)
    task_ctx, task_idx = [], []   # parallel: context (g,X_LEN) and (s, group)
    done = 0

    def _flush():
        nonlocal done
        if not task_ctx:
            return
        _, mean = pipeline.predict_quantiles(
            task_ctx, prediction_length=Y_LEN, quantile_levels=[0.5],
            batch_size=batch_size)
        for (s, grp), m in zip(task_idx, mean):
            out[s, grp, :] = m.float().cpu().numpy()  # (|grp|, Y_LEN)
        done += len(task_ctx)
        task_ctx.clear()
        task_idx.clear()
        print(f"[chronos]   forecast {done}/{total_tasks} groups "
              f"({S} windows x {len(groups)} groups)", flush=True)

    for s in range(S):
        xs = test_x[s]  # (X_LEN, N)
        for grp in groups:
            task_ctx.append(np.ascontiguousarray(xs[:, grp].T))  # (|grp|, X_LEN)
            task_idx.append((s, grp))
            if len(task_ctx) >= tasks_per_call:
                _flush()
    _flush()
    return out


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #
def resolve_paths(dataset):
    ds = dataset.lower()
    # TFNSW lives at the repo root (../tfnsw), not under xxltrafficdata/preprocessed/.
    base = "../tfnsw" if ds == "tfnsw" else f"../xxltrafficdata/preprocessed/{ds}"
    return {
        "raw": f"{base}/RawData/",
        "fast": f"{base}/FastData/",
        "graph": f"{base}/graph/",
    }


def build_groups(grouping, graph_path, year, n_nodes, group_size):
    """Return list of node-index groups for one year (multivariate mode)."""
    if grouping == "index":
        return index_groups(n_nodes, group_size)
    # graph-aware (default)
    adj_fp = os.path.join(graph_path, f"{year}_adj.npz")
    if not os.path.exists(adj_fp):
        print(f"[chronos]   WARN: {adj_fp} missing — falling back to index grouping",
              flush=True)
        return index_groups(n_nodes, group_size)
    adj = np.load(adj_fp)["x"]
    assert adj.shape[0] == n_nodes, \
        f"adj nodes {adj.shape[0]} != data nodes {n_nodes} for {year}"
    return graph_groups(adj, group_size)


def discover_years(raw_path):
    ys = []
    for fn in os.listdir(raw_path):
        if fn.endswith(".npz") and fn[:-4].isdigit():
            ys.append(int(fn[:-4]))
    return sorted(ys)


def append_csv_row(csv_path, row, header):
    new = not os.path.exists(csv_path)
    with open(csv_path, "a", newline="") as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        w = csv.DictWriter(f, fieldnames=header)
        if new:
            w.writeheader()
        w.writerow(row)
        fcntl.flock(f, fcntl.LOCK_UN)


def main():
    ap = argparse.ArgumentParser(description="Chronos-2 zero-shot baseline")
    ap.add_argument("--dataset", required=True, help="e.g. pems03 (case-insensitive)")
    ap.add_argument("--year", type=int, default=None, help="single year; default = all years")
    ap.add_argument("--begin-year", type=int, default=None)
    ap.add_argument("--end-year", type=int, default=None)
    ap.add_argument("--model", default="amazon/chronos-2", help="HF model id")
    ap.add_argument("--gpuid", type=int, default=0)
    ap.add_argument("--device", default=None, help="override, e.g. cpu / cuda:0")
    ap.add_argument("--mode", default="multivariate",
                    choices=["univariate", "multivariate"],
                    help="multivariate = share info across spatially-grouped nodes "
                         "(Chronos-2's headline feature); univariate = per-node")
    ap.add_argument("--grouping", default="graph", choices=["graph", "index"],
                    help="multivariate node grouping: graph (BFS over per-year adj, "
                         "spatially coherent) or index (contiguous chunks)")
    ap.add_argument("--group-size", type=int, default=64,
                    help="variates per multivariate task (Chronos-2 pretrain "
                         "group size is ~100s; large groups are OOD)")
    ap.add_argument("--batch-size", type=int, default=512,
                    help="number of series (variates summed) per Chronos call")
    ap.add_argument("--dtype", default="bfloat16", choices=["float32", "bfloat16", "float16"])
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--out-dir", default="run_logs/chronos")
    ap.add_argument("--no-verify", action="store_true", help="skip FastData reconstruction check")
    ap.add_argument("--max-windows", type=int, default=0,
                    help="DEBUG ONLY: cap test windows per year (0 = use all). "
                         "Non-zero makes numbers NOT comparable; logged loudly.")
    args = ap.parse_args()

    import torch
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    if args.device:
        device = args.device
    elif torch.cuda.is_available():
        device = f"cuda:{args.gpuid}"
    else:
        device = "cpu"
    dtype = {"float32": torch.float32, "bfloat16": torch.bfloat16,
             "float16": torch.float16}[args.dtype]

    paths = resolve_paths(args.dataset)
    if not os.path.isdir(paths["raw"]):
        sys.exit(f"[err] raw data path not found: {paths['raw']}")

    if args.year is not None:
        years = [args.year]
    else:
        years = discover_years(paths["raw"])
        if args.begin_year is not None:
            years = [y for y in years if y >= args.begin_year]
        if args.end_year is not None:
            years = [y for y in years if y <= args.end_year]
    if not years:
        sys.exit("[err] no years to run")

    ds_lower = args.dataset.lower()
    out_dir = os.path.join(args.out_dir, ds_lower)
    os.makedirs(out_dir, exist_ok=True)
    csv_path = os.path.join(out_dir, f"{ds_lower}_results.csv")
    csv_header = ["dataset", "year", "model", "mode", "grouping", "group_size",
                  "seed", "n_samples", "n_nodes", "n_groups",
                  "T3_MAE", "T3_RMSE", "T3_MAPE", "T6_MAE", "T6_RMSE", "T6_MAPE",
                  "T12_MAE", "T12_RMSE", "T12_MAPE", "Avg_MAE", "Avg_RMSE",
                  "Avg_MAPE", "secs"]

    grp_desc = (f"mode={args.mode} grouping={args.grouping} group_size={args.group_size}"
                if args.mode == "multivariate" else "mode=univariate")
    print(f"[chronos] dataset={ds_lower} years={years} model={args.model} "
          f"device={device} dtype={args.dtype} bs={args.batch_size} {grp_desc}",
          flush=True)

    print(f"[chronos] loading {args.model} ...", flush=True)
    pipeline = load_pipeline(args.model, device, dtype)
    print("[chronos] model loaded.", flush=True)

    for year in years:
        t0 = time.time()
        test_x, test_y = build_test_windows(
            paths["raw"], year, paths["fast"], verify=not args.no_verify)
        if args.max_windows and test_x.shape[0] > args.max_windows:
            print(f"[chronos] !! DEBUG --max-windows={args.max_windows}: using "
                  f"{args.max_windows}/{test_x.shape[0]} windows — numbers are "
                  f"NOT comparable to the full benchmark.", flush=True)
            test_x = test_x[:args.max_windows]
            test_y = test_y[:args.max_windows]
        S, _, N = test_x.shape
        gt = np.transpose(test_y, (0, 2, 1))  # (S, N, Y_LEN)

        test_x, n_bad = impute_windows(test_x)
        if n_bad:
            print(f"[chronos]   imputed {n_bad}/{S * N} (window,node) contexts "
                  f"with missing values (context-mean fill)", flush=True)

        n_groups = 0
        if args.mode == "multivariate":
            groups = build_groups(args.grouping, paths["graph"], year, N,
                                  args.group_size)
            n_groups = len(groups)
            print(f"[chronos] {ds_lower} {year}: {S} windows x {N} nodes in "
                  f"{n_groups} groups ({args.grouping}, size~{args.group_size}) "
                  f"= {S * n_groups} multivariate tasks", flush=True)
            pred = forecast_multivariate(pipeline, test_x, groups, args.batch_size)
        else:
            print(f"[chronos] {ds_lower} {year}: {S} windows x {N} nodes "
                  f"= {S * N} univariate series", flush=True)
            pred = forecast_univariate(pipeline, test_x, args.batch_size)

        metrics = cal_metric(gt, pred)
        secs = time.time() - t0
        for T in ("3", "6", "12", "Avg"):
            m = metrics[T]
            print(f"[chronos] {ds_lower} {year} T:{T}\tMAE {m['MAE']:.4f}\t"
                  f"RMSE {m['RMSE']:.4f}\tMAPE {m['MAPE']:.4f}", flush=True)
        print(f"[chronos] {ds_lower} {year} done in {secs:.1f}s", flush=True)

        meta = {"dataset": ds_lower, "year": year, "model": args.model,
                "mode": args.mode,
                "grouping": args.grouping if args.mode == "multivariate" else "",
                "group_size": args.group_size if args.mode == "multivariate" else 0,
                "seed": args.seed, "n_samples": int(S), "n_nodes": int(N),
                "n_groups": int(n_groups)}
        rec = dict(meta, secs=round(secs, 1), metrics=metrics)
        tag = args.mode if args.mode == "univariate" else f"mv_{args.grouping}{args.group_size}"
        with open(os.path.join(out_dir, f"{ds_lower}_{year}_{tag}.json"), "w") as f:
            json.dump(rec, f, indent=2)

        row = dict(meta, secs=round(secs, 1))
        for T in ("3", "6", "12", "Avg"):
            row[f"{'T' + T if T != 'Avg' else 'Avg'}_MAE"] = round(metrics[T]["MAE"], 4)
            row[f"{'T' + T if T != 'Avg' else 'Avg'}_RMSE"] = round(metrics[T]["RMSE"], 4)
            row[f"{'T' + T if T != 'Avg' else 'Avg'}_MAPE"] = round(metrics[T]["MAPE"], 4)
        append_csv_row(csv_path, row, csv_header)

    print(f"[chronos] all done. results -> {out_dir}", flush=True)


if __name__ == "__main__":
    main()
